#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "flus"
name = "Flus"
description.en = "Aggregate, save and share links from all over the Web"
description.fr = "Agréger, enregistrer et partager des liens de partout sur le Web"

version = "2.2.1~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://flus.fr/"
demo = "https://demo.flus.fr/"
code = "https://github.com/flusio/Flus"
fund = "https://flus.fr/tarifs"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/flus"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/flusio/Flus/archive/refs/tags/v2.2.1.tar.gz"
    sha256 = "3d8fc2de27165fd3fd399bf0f543442af3175a744f8bf6a1644d645c344c681f"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, php8.4-gettext, php8.4-gd, php8.4-intl, php8.4-pgsql"

    [resources.database]
    type = "postgresql"

    [resources.composer]
    version = "2.9.5"
    